[package]
name = "day_12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path="../common"}
derive-new = "0.6.0"
itertools = "0.12.0"
rayon = "1.8.0"
